server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      port: 27017
      username: kuwa
      password: kuwapassword
      host: localhost
      authentication-database: appdb
      database: appdb
    rest:
      base-path: /api

#  devtools:
#    remote:
#      proxy:
#        host: localhost
#        port: 8080
#      restart:
#        enabled: true
#    livereload:         # Hot Reload
#      enabled: true
#    restart:            # Hot Reload
#      enabled: true

  batch:
    jdbc:
      initialize-schema: always

  graphql:
    graphiql:
      enabled: true

  ##  in use H2
#  datasource:
#    url: jdbc:h2:mem:sample_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  sql:
#    init:
#      encoding: utf-8
#      mode: always
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        trace: true
#        web-allow-others: true
#      path: /h2-console

#  in use mariadb
  datasource:
    username: root
    password: mariapassword
    url: jdbc:mariadb://localhost:3306/sampledb
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      encoding: utf-8
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

## in use postgresql
#  datasource:
#    url: jdbc:postgresql://postgres:5432/sampledb
#    username: postgres
#    password: root
#    driverClassName: org.postgresql.Driver